### ISSUE TITLE
Error: Cannot find module 'prettier/parser-babel'

### ISSUE THREAD

**Issue by rerodrigues** [ggascoigne/prettier-plugin-import-sort#12]
I don't know exactly why this happens, but when running prettier via eslint --fix I got this error.

the error is trown by prettier-plugin-import-sort/src/index.js line
```
const { parsers: javascriptParsers } = _interopDefault(
  require('prettier/parser-babel')
)
```

even I'm using TS

below is my conf on package.json

```
  "importSort": {
    ".ts, .tsx": {
      "style": "renke",
      "parser": "typescript"
    }
  },
```

and my lint-staged config which is firing the eslint --fix
```
  "lint-staged": {
    "*.{js,ts,tsx,jsx}": [
      "eslint --fix"
    ]
  },
```
EDIT:  Even if I run `$(npm bin)/prettier ` manually, the same error happens

**Comment by ggascoigne** [comment]
Not at my computer right now, but I’m guessing that you aren’t using the
latest versions of prettier and prettier-plugin-import-sort.

**Comment by kevinfarrugia** [comment]
I have received the same error and it was resolved by updating to prettier: ^2.x.x (previously was on prettier 1.x.x).

**Comment by c10b10** [comment]
This error was fixed by using the latest version of Pettier, but I'm now getting `TypeError: style is not a function`.

**Comment by malthejorgensen** [comment]
@c10b10 Had the same issue just now. The mistake was that I hadn't used the right format for the `importSort` config in `package.json`. It doesn't tell you if it's malformed and then falls back to `node_modules/eslint/lib/api.js` as the style, which doesn't work.

**Not working**
```javascript
// package.json
"importSort": {
  "*.js": {
    "style": "module",
  }
},
```

**Working**
```javascript
// package.json
"importSort": {
  ".js": {
    "style": "module",
  }
},
```

**Comment by ggascoigne** [comment]
Thanks for pointing this out, I'll make note of this in the readme.

**Comment by ggascoigne** [comment]
FYI the next release is going to drop prettier v1 support, v2 has been out long enough now that this shouldn't be too much of a problem.
