### ISSUE TITLE
Custom style from github could not be resolved

### ISSUE THREAD

**Issue by jdselig** [ggascoigne/prettier-plugin-import-sort#18]
Hi there! 

Thanks for your work on this plugin! I created a custom style for my company, and then hosted it on our Github. I've added it to our package.json, and have confirmed that it's getting added to the project correctly when I run `yarn`. However, changing the `style` key in the `importSort` section of package.json to the custom style fails (whereas using an existing one from npm, like `import-sort-style-module` and the like all work fine). 

Do you have any suggestions for how to work around this? Thank you!

**Comment by ggascoigne** [comment]
does it get picked up correctly if you just run import-sort directly?

**Comment by jdselig** [comment]
Ah, it doesn't actually 😅 Sorry, just found this stuff today. I'm guessing it's an issue with loading the custom package via Git, but I could just be missing a step. Thank you for replying!
