### ISSUE TITLE
interleave code between imports

### ISSUE THREAD

**Issue by safareli** [ggascoigne/prettier-plugin-import-sort#19]
If you have:

```js
import("foo")
// prettier-ignore
console.log("biz")
import("bar")
```

Despite what you have in styles, you would get the console.log to be pushed at the end of imports
```js
import("foo")
import("bar")

// prettier-ignore
console.log("biz")
```

is there something one can do to put non import code in between imports?

**Comment by ggascoigne** [comment]
That really is an issue with import-sort itself, you should take it over to https://github.com/renke/import-sort
