### ISSUE TITLE
Update for prettier v3.0.0

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [ggascoigne/prettier-plugin-import-sort#28]
Hi,

thanks for cool plugin,

do you plan to upgrade it to be compatible with prettier v3.0.0?

**Comment by barona-mika-vilpas** [comment]
Is there something that is not working for you?
I am using this in a project with the following versions and it seems to work:
- prettier `3.1.0`
- prettier-plugin-import-sort `0.0.7`

Settings from package.json:
```json
  "importSort": {
    ".js, .jsx, .ts, .tsx": {
      "style": "module",
      "parser": "typescript"
    }
  }
```

.prettierrc
```json
{
  "printWidth": 120,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "endOfLine": "lf",
  "proseWrap": "always",
  "plugins": ["prettier-plugin-import-sort"]
}
```

**Comment by AdaskoTheBeAsT** [comment]
:) I will need to recheck

**Comment by AdaskoTheBeAsT** [comment]
it is working again :) something was initially not working in prettier 3.0.x  cool

**Comment by u8675309** [comment]
With prettier 3, [Plugin search feature has been removed](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker).

If your prettier config previously said ```"plugins": []```, it would work before prettier 3, but now you have to list every plugin like ```"plugins": ["prettier-plugin-import-sort"]```.

**Comment by AdaskoTheBeAsT** [comment]
closing - everything works :)
