### ISSUE TITLE
Not compatible with Prettier v2

### ISSUE THREAD

**Issue by euangoddard** [ggascoigne/prettier-plugin-import-sort#8]
Prettier have changed their API and, as a result, sorting no longer works.

Relevant changes are [here](https://prettier.io/blog/2020/03/21/2.0.0.html#remove-deprecated-options-and-option-values-6993httpsgithubcomprettierprettierpull6993-7511httpsgithubcomprettierprettierpull7511-7533httpsgithubcomprettierprettierpull7533-7535httpsgithubcomprettierprettierpull7535-7536httpsgithubcomprettierprettierpull7536-by-fiskerhttpsgithubcomfisker).

I will make a PR as the change is very small to fix it

**Comment by euangoddard** [comment]
Looks like @thebuilder has already addressed this in #7

**Comment by ggascoigne** [comment]
Fixed in v0.0.4.

Thank you for the report.
