### ISSUE TITLE
import-sort-ignore not working

### ISSUE THREAD

**Issue by sachaw** [ggascoigne/prettier-plugin-import-sort#9]
Not sure if it's an issue with you package, however that is what I'm using.
Any file containing a comment with the content `import-sort-ignore` should be excluded

**Comment by ggascoigne** [comment]
I didn't actually know that this option existed, that said, I just tried it in one of my projects by adding  `// import-sort-ignore` to some files.  They were still formatted by prettier, but their imports were not re-ordered by import-sorts.

In other words, as far as I can tell the options works for me.  This was tested with prettier@2.0.1

**Comment by sachaw** [comment]
Ok, great, I'll take this issue elsewhere than, thanks.

**Comment by golergka** [comment]
@sachaw have you been able to reproduce this? I'm seeing the same issue
